# Automated Reporting System Configuration

storage:
  base_path: "./data"
  rupee_folder: "rupee_value"
  thousands_folder: "thousands_value"

excel:
  templates_path: "./templates"
  default_template: "report_template.xlsx"

bots:
  erp:
    url: "https://erp.company.com"
    timeout: 30
  scienter:
    url: "https://scienter.company.com"
    timeout: 30
  sasianet:
    url: "https://sasianet.company.com"
    timeout: 30

reports:
  Report01:
    bot: "erp"
    schedule: "0 8 * * *"  # Daily at 8 AM
    enabled: true
  Report02:
    bot: "scienter"
    schedule: "0 9 * * *"  # Daily at 9 AM
    enabled: true
  Report03:
    bot: "sasianet"
    schedule: "0 10 * * *"  # Daily at 10 AM
    enabled: true

logging:
  level: "INFO"
  file: "./logs/app.log"
  max_size: "10MB"
  backup_count: 5

api:
  title: "Automated Reporting System API"
  version: "1.0.0"
  description: "API for managing automated reports"